### ISSUE TITLE
Erro ao executar o teste na estação

### ISSUE THREAD

**Issue by lunebrille** [RaphaelMolina/P.I#1]
Ao tentar rodar no PC, não encontrei o banco para fazer a importação para rodar o teste em php. Poderia encaminhar a atualização do arquivo para fazer o teste?

**Comment by RaphaelMolina** [comment]
Olá Daniele, tem dois arquivos do banco, um com insert (dados inseridos) e um sem.
Os arquivos do banco tem a extensão .sql
